---
- name: Get VirtualBox version.
  command: cat /home/vagrant/.vbox_version
  changed_when: false
  register: virtualbox_version

- name: Mount VirtualBox guest additions ISO.
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    opts: loop
    state: mounted
    fstype: iso9660

- name: Run VirtualBox guest additions installation.
  command: sh /tmp/vbox/VBoxLinuxAdditions.run
  changed_when: true

- name: Unmount VirtualBox guest additions ISO.
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    state: absent
    fstype: iso9660

- name: Delete VirtualBox guest additions ISO.
  file:
    path: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    state: absent
